import { createClient } from './client'
import type { CvRow } from './rows'
import type { ParsedCv, TargetRole } from '@/lib/types'

export async function listCvsForProfile(profileId: string): Promise<CvRow[]> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('cvs')
    .select('*')
    .eq('profile_id', profileId)
    .order('version', { ascending: false })

  if (error) throw new Error(`listCvsForProfile(${profileId}): ${error.message}`)
  return (data ?? []) as CvRow[]
}

export async function getCvById(id: string): Promise<CvRow | null> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('cvs')
    .select('*')
    .eq('id', id)
    .maybeSingle()

  if (error) throw new Error(`getCvById(${id}): ${error.message}`)
  return (data as CvRow | null) ?? null
}

export type SaveCvInput = {
  id: string
  profileId: string
  targetRole: TargetRole | null
  rawText: string | null
  parsedData: ParsedCv
  filePath: string | null
}

// Persists a freshly uploaded CV: computes the next version for the profile,
// archives any previously active CV (one active per profile is a UI
// convention), and inserts the new row as the active one. `id` is generated by
// the caller so the Storage path can be built before the row exists.
export async function saveCv(input: SaveCvInput): Promise<CvRow> {
  const supabase = await createClient()

  const { data: latest, error: versionError } = await supabase
    .from('cvs')
    .select('version')
    .eq('profile_id', input.profileId)
    .order('version', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (versionError) {
    throw new Error(`saveCv(version lookup): ${versionError.message}`)
  }
  const nextVersion = (latest?.version ?? 0) + 1

  const { error: archiveError } = await supabase
    .from('cvs')
    .update({ status: 'archived' })
    .eq('profile_id', input.profileId)
    .eq('status', 'active')

  if (archiveError) {
    throw new Error(`saveCv(archive previous): ${archiveError.message}`)
  }

  const { data, error } = await supabase
    .from('cvs')
    .insert({
      id: input.id,
      profile_id: input.profileId,
      version: nextVersion,
      status: 'active',
      target_role: input.targetRole,
      file_path: input.filePath,
      raw_text: input.rawText,
      parsed_data: input.parsedData,
    })
    .select('*')
    .single()

  if (error) throw new Error(`saveCv(insert): ${error.message}`)
  return data as CvRow
}

// Bucket the uploaded PDFs live in — mirrors STORAGE_BUCKET in
// app/api/cvs/route.ts and lib/db/storage.ts.
const STORAGE_BUCKET = 'cvs'

// Deletes a CV: removes its stored PDF (best-effort) and the row itself. The
// row's analyses cascade away on the DB side (analyses.cv_id ON DELETE CASCADE).
// If the deleted CV was the active one, the most recent remaining version is
// promoted to active so the profile keeps one active CV — the same
// one-active-per-profile convention saveCv enforces. Returns the profile and the
// promoted CV's id (if any) so callers can resync.
export async function deleteCv(
  id: string,
): Promise<{ profileId: string; promotedCvId: string | null }> {
  const supabase = await createClient()

  // Fetch first: we need profile_id + status (whether to promote a replacement)
  // and file_path (which stored PDF to remove) before the row is gone.
  const { data: cv, error: fetchError } = await supabase
    .from('cvs')
    .select('id, profile_id, status, file_path')
    .eq('id', id)
    .maybeSingle()

  if (fetchError) throw new Error(`deleteCv(fetch ${id}): ${fetchError.message}`)
  if (!cv) throw new Error(`deleteCv: CV ${id} not found.`)

  if (cv.file_path) {
    const { error: storageError } = await supabase.storage
      .from(STORAGE_BUCKET)
      .remove([cv.file_path])
    // Best-effort: a missing/failed file shouldn't block deleting the record.
    if (storageError) {
      console.error(`deleteCv(storage ${cv.file_path}): ${storageError.message}`)
    }
  }

  const { error: deleteError } = await supabase.from('cvs').delete().eq('id', id)
  if (deleteError) throw new Error(`deleteCv(delete ${id}): ${deleteError.message}`)

  let promotedCvId: string | null = null
  if (cv.status === 'active') {
    const { data: next, error: nextError } = await supabase
      .from('cvs')
      .select('id')
      .eq('profile_id', cv.profile_id)
      .order('version', { ascending: false })
      .limit(1)
      .maybeSingle()

    if (nextError) throw new Error(`deleteCv(promote lookup): ${nextError.message}`)

    if (next) {
      const { error: promoteError } = await supabase
        .from('cvs')
        .update({ status: 'active' })
        .eq('id', next.id)
      if (promoteError) throw new Error(`deleteCv(promote ${next.id}): ${promoteError.message}`)
      promotedCvId = next.id
    }
  }

  return { profileId: cv.profile_id, promotedCvId }
}
